/*********************************************************************************
    This file is part of Open Mobile.

    Open Mobile is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Open Mobile is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Open Mobile.  If not, see <http://www.gnu.org/licenses/>.
 
    There is one additional restriction when using this framework regardless of modifications to it.
    The About Panel or its contents must be easily accessible by the end users.
    This is to ensure all project contributors are given due credit not only in the source code.
*********************************************************************************/
using System;
using System.Collections.Generic;
using System.Text;
using OpenMobile;
using OpenMobile.Plugin;
using OpenMobile.Controls;
using OpenMobile.Graphics;

namespace OpenMobile.Zones
{
    /// <summary>
    /// A zone is a object consisting of one or more Screens and AudioUnits
    /// /// </summary>
    public class Zone
    {
        /// <summary>
        /// Screen that's assosiated with this zone
        /// </summary>
        private int _Screen = -1;

        /// <summary>
        /// Audiodevice (instance number) that's assosiated with this zone
        /// </summary>
        private int _AudioDevice = -1;

        /// <summary>
        /// Name of the zone
        /// </summary>
        private string _Name = "";

        /// <summary>
        /// List of zone's (names) that's included in this zone
        /// </summary>
        private List<string> _Includes = new List<string>();

        /// <summary>
        /// True = zone is autogenerated from OM
        /// </summary>
        public bool AutoGenerated { get; set; }

        /// <summary>
        /// List of zone's (names) that's included in this zone
        /// </summary>
        public List<string> Includes
        {
            get
            {
                return _Includes;
            }
            set
            {
                _Includes = value;
            }
        }

        /// <summary>
        /// Name of the zone
        /// </summary>
        public string Name 
        {
            get
            {
                return _Name;
            }
            set
            {
                if (!AutoGenerated)
                    _Name = value;
            }
        }

        /// <summary>
        /// Screen number for this zone (Currently only one screen pr zone is supported)
        /// </summary>
        public int Screen
        {
            get
            {
                return _Screen;
            }
        }

        /// <summary>
        /// AudioDevice number for this zone (Currently only one device pr zone is supported)
        /// </summary>
        public int AudioDevice
        {
            get
            {
                return _AudioDevice;
            }
        }

        /// <summary>
        /// Register a zone as included in this zone (must be uniqe)
        /// </summary>
        /// <param name="zone"></param>
        /// <returns></returns>
        public bool Add(Zone zone)
        {
            // See if this zone already exists
            string ZoneCheck = _Includes.Find(a => a == zone.Name);
            if (ZoneCheck != null)
                return false;   // No, return error

            // New zone, add it
            _Includes.Add(zone.Name);

            // All good, return true
            return true;
        }

        /// <summary>
        /// Create a new zone, specifying the default screen and audiodevice
        /// </summary>
        /// <param name="Name">Name of xone</param>
        /// <param name="Screen">Main screen</param>
        /// <param name="AudioDevice">Main audio device</param>
        public Zone(string Name, int Screen, int AudioDevice)
        {
            _Name = Name;
            _Screen = Screen;
            _AudioDevice = AudioDevice;
        }

        /// <summary>
        /// Do not use this constructor, included only for serialization
        /// </summary>
        private Zone()
        {
        }

        /// <summary>
        /// ToString
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return _Name;
        }
    }
}
